// Generated by CoffeeScript 2.5.1
(function() {
  var onCloseClick, onScrollTopClick;

  onCloseClick = function() {
    window.history.go(-1);
    return false;
  };

  onScrollTopClick = function() {
    document.body.scrollTop = 0; // For Safari
    return document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
  };

  $("close-btn").click(onCloseClick);

  $("scrollTop-btn").click(onScrollTopClick);

}).call(this);
