// Generated by CoffeeScript 2.5.1
(function() {
  //: import flexibel.coffee
  var searchInputClear, startSearch;

  startSearch = function() {
    var entries, entry, firstTest, i, input, len, ref, results, secondTest;
    input = new RegExp(valueof("search-input"), "i");
    entries = element("dict-entries");
    ref = entries.children;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      entry = ref[i];
      firstTest = input.test(entry.children[0].innerText);
      secondTest = input.test(entry.children[1].innerText);
      entry.hidden = false;
      if (!(firstTest || secondTest)) {
        results.push(entry.hidden = true);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  searchInputClear = function(event) {
    var searchInput;
    searchInput = document.getElementById("search-input");
    searchInput.value = "";
    return startSearch();
  };

  document.getElementById("search-input").addEventListener("input", startSearch);

  document.getElementById("search-button").addEventListener("click", startSearch);

  document.getElementById("search-clear").addEventListener("click", searchInputClear);

}).call(this);
