// Generated by CoffeeScript 2.5.1
(function() {
  /*
  	Yield application
  	Autor: Tsvikevich Denis 2020
  */
  var clearError, evalPotentialYield, fail, runApplication;

  //: import flexibel.coffee
  runApplication = function() {
    return evalPotentialYield();
  };

  fail = function(error) {
    htmlset("errorlogs", `<p style="color: red;">${error}</p>`);
    return false;
  };

  clearError = function() {
    return fail("");
  };

  evalPotentialYield = function() {
    var coeffpar, cval, par, partadd, py, pyadd, pybase, wetbase;
    par = runParser(valueof("par"));
    coeffpar = runParser(valueof("coeff-par"));
    cval = runParser(valueof("cval"));
    wetbase = runParser(valueof("wetbase"));
    partadd = runParser(valueof("partadd"));
    py = (par * coeffpar) / (1000 * cval);
    pybase = (py * 100) / ((100 - wetbase) * (1 + partadd));
    pyadd = pybase * partadd;
    return htmlset("result", `ПУ = ${py}<br>ПУ<sub>осн</sub> = ${pybase}<br>ПУ<sub>поб</sub> = ${pyadd}`);
  };

  element("runButton").addEventListener("click", runApplication);

}).call(this);
